Msj 210 azure key vault
cloudmatos/matos-azure-provider pull request #2
Opened 2022-09-08 10:02 UTC by Ashishcloudmatos

2022-09-08 11:50 UTC, dungdmatos commented
Hey @AshishBotMantra could you remove the .ideal folder

2022-09-08 14:07 UTC, dungdmatos approved these changes

2022-09-08 14:29 UTC, rajesh-bagavathiyappan requested changes

2022-09-08 14:29 UTC, rajesh-bagavathiyappan commented on requirement.txt
> +azure-identity
this file is not required

2022-09-08 14:29 UTC, rajesh-bagavathiyappan commented on src/matos_azure_provider/provider.py
> +    def __init__(self, **kwargs):
retain the return type

`def __init__(self, **kwargs) -> None:`

2022-09-08 14:29 UTC, rajesh-bagavathiyappan commented on src/matos_azure_provider/provider.py
> +        print(service_map)
remove temporary code

2022-09-08 14:41 UTC, Ashishcloudmatos commented on requirement.txt
> +azure-identity
deleted plz review it now

2022-09-09 13:29 UTC, rajesh-bagavathiyappan approved these changes

2022-09-09 13:29 UTC, merged